using CSharpCodeAnalyst.CodeGraph.Graph;
using CSharpCodeAnalyst.CodeParser.Parser;
using CSharpCodeAnalyst.CodeParser.Parser.Config;

namespace CodeParserTests.UnitTests.Parser;

/// <summary>
///     Generated code is always parsed - it holds relationships nothing else does - and marked instead, so
///     a result can leave out what nobody can edit anyway.
/// </summary>
[TestFixture]
public class GeneratedCodeTests
{
    private const string Code = """
                                namespace Demo;

                                public class Widget
                                {
                                    public void Run() { }
                                }
                                """;

    private static async Task<CodeElement> ParseWidget(string code, string documentPath)
    {
        var parser = new CSharpCodeAnalyst.CodeParser.Parser.Parser(
            new ParserConfig(new ProjectExclusionRegExCollection(), false));
        var result = await parser.ParseSourceAsync(code, documentPath);

        return result.CodeGraph.Nodes.Values.Single(n => n.Name == "Widget");
    }

    [Test]
    public async Task Parse_HandWrittenFile_IsNotMarked()
    {
        Assert.That((await ParseWidget(Code, "Widget.cs")).IsGenerated, Is.False);
    }

    [TestCase("Widget.g.cs")]
    [TestCase("Widget.g.i.cs")]
    [TestCase("Widget.Designer.cs")]
    [TestCase("Widget.generated.cs")]
    [TestCase("TemporaryGeneratedFile_Widget.cs")]
    public async Task Parse_GeneratedFileName_IsMarked(string documentPath)
    {
        Assert.That((await ParseWidget(Code, documentPath)).IsGenerated, Is.True);
    }

    [Test]
    public async Task Parse_AutoGeneratedHeader_IsMarked()
    {
        // What catches the files the name list does not - the AssemblyInfo under obj, and anything a tool
        // writes under its own name.
        var code = "// <auto-generated />" + Environment.NewLine + Code;

        Assert.That((await ParseWidget(code, "Widget.cs")).IsGenerated, Is.True);
    }

    [Test]
    public async Task Parse_AutoGeneratedCommentBelowTheFirstToken_IsNotMarked()
    {
        // Otherwise a file merely talking about generated code would count.
        var code = Code + Environment.NewLine + "// <auto-generated> is what a tool would write here.";

        Assert.That((await ParseWidget(code, "Widget.cs")).IsGenerated, Is.False);
    }

    /// <summary>
    ///     The partial case, which is why the rule asks about *every* declaration: a WPF code-behind class
    ///     lives in MainWindow.xaml.cs and MainWindow.g.cs at once. Only what exists nowhere but the
    ///     generated file is generated.
    /// </summary>
    [Test]
    public void IsGeneratedElement_DecidesOverAllDeclarations()
    {
        var generatedFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { @"C:\p\MainWindow.g.cs" };

        var partialType = Element(@"C:\p\MainWindow.xaml.cs", @"C:\p\MainWindow.g.cs");
        var generatedOnly = Element(@"C:\p\MainWindow.g.cs");
        var handWritten = Element(@"C:\p\MainWindow.xaml.cs");
        var withoutLocation = Element();

        Assert.Multiple(() =>
        {
            Assert.That(GeneratedCode.IsGeneratedElement(partialType, generatedFiles), Is.False);
            Assert.That(GeneratedCode.IsGeneratedElement(generatedOnly, generatedFiles), Is.True);
            Assert.That(GeneratedCode.IsGeneratedElement(handWritten, generatedFiles), Is.False);

            // An assembly or a namespace has no declaration of its own.
            Assert.That(GeneratedCode.IsGeneratedElement(withoutLocation, generatedFiles), Is.False);
        });
    }

    private static CodeElement Element(params string[] files)
    {
        var element = new CodeElement("id", CodeElementType.Class, "MainWindow", "MainWindow", null);
        element.SourceLocations.AddRange(files.Select(file => new SourceLocation(file, 1, 1)));
        return element;
    }
}
