//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpCodeAnalyst.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpCodeAnalyst.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _parent.
        /// </summary>
        public static string AddParent {
            get {
                return ResourceManager.GetString("AddParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add selected to graph.
        /// </summary>
        public static string AddSelectedToGraph_Label {
            get {
                return ResourceManager.GetString("AddSelectedToGraph_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected to graph (_collapsed).
        /// </summary>
        public static string AddSelectedToGraphCollapsed_Label {
            get {
                return ResourceManager.GetString("AddSelectedToGraphCollapsed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add to Code Explorer.
        /// </summary>
        public static string AddToGraph_MenuItem {
            get {
                return ResourceManager.GetString("AddToGraph_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All in_coming relationships.
        /// </summary>
        public static string AllIncomingRelationships {
            get {
                return ResourceManager.GetString("AllIncomingRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All incoming relationships (deep).
        /// </summary>
        public static string AllIncomingRelationshipsDeep {
            get {
                return ResourceManager.GetString("AllIncomingRelationshipsDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All out_going relationships.
        /// </summary>
        public static string AllOutgoingRelationships {
            get {
                return ResourceManager.GetString("AllOutgoingRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All outgoing relationships (deep).
        /// </summary>
        public static string AllOutgoingRelationshipsDeep {
            get {
                return ResourceManager.GetString("AllOutgoingRelationshipsDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule text cannot be empty.
        /// </summary>
        public static string Analyzer_Empty_Rule {
            get {
                return ResourceManager.GetString("Analyzer_Empty_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event registrations.
        /// </summary>
        public static string Analyzer_EventRegistration_Label {
            get {
                return ResourceManager.GetString("Analyzer_EventRegistration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds imbalances between number of event registrations / un-registrations.
        /// </summary>
        public static string Analyzer_EventRegistration_Tooltip {
            get {
                return ResourceManager.GetString("Analyzer_EventRegistration_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzers.
        /// </summary>
        public static string Analyzers_Label {
            get {
                return ResourceManager.GetString("Analyzers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Code Analyst.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three rules are supported:
        ///
        ///DENY: Forbids dependencies from source to target
        ///RESTRICT: Allows only specified dependencies
        ///ISOLATE: Completely isolates the source from external dependencies
        ///
        ///Patterns:
        ///MyApp.Business → exact match
        ///MyApp.Business.* → element + direct children
        ///MyApp.Business.** → element + all descendants
        ///
        ///Examples:
        ///DENY: MyApp.Business.** -&gt; MyApp.Data.**
        ///RESTRICT: MyApp.Controllers.** -&gt; MyApp.Services.**
        ///ISOLATE: MyApp.Domain.**.
        /// </summary>
        public static string ArchitectureRules_Info {
            get {
                return ResourceManager.GetString("ArchitectureRules_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom to Top.
        /// </summary>
        public static string Bottom_To_Top_Label {
            get {
                return ResourceManager.GetString("Bottom_To_Top_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse ....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear_Label {
            get {
                return ResourceManager.GetString("Clear_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the content of the graph.
        /// </summary>
        public static string Clear_Tooltip {
            get {
                return ResourceManager.GetString("Clear_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Flags.
        /// </summary>
        public static string ClearAllFlags {
            get {
                return ResourceManager.GetString("ClearAllFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search.
        /// </summary>
        public static string ClearSearch_Tooltip {
            get {
                return ResourceManager.GetString("ClearSearch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_Button {
            get {
                return ResourceManager.GetString("Close_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis completed with exit code: {0}.
        /// </summary>
        public static string Cmd_AnalysisComplete {
            get {
                return ResourceManager.GetString("Cmd_AnalysisComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser failures:.
        /// </summary>
        public static string Cmd_Failures {
            get {
                return ResourceManager.GetString("Cmd_Failures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules file: {0}.
        /// </summary>
        public static string Cmd_RulesFile {
            get {
                return ResourceManager.GetString("Cmd_RulesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules file not found..
        /// </summary>
        public static string Cmd_RulesFileNotFound {
            get {
                return ResourceManager.GetString("Cmd_RulesFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution file: {0}.
        /// </summary>
        public static string Cmd_SolutionFile {
            get {
                return ResourceManager.GetString("Cmd_SolutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution file not found..
        /// </summary>
        public static string Cmd_SolutionFileNotFound {
            get {
                return ResourceManager.GetString("Cmd_SolutionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command to execute is unknown or the required parameters are missing..
        /// </summary>
        public static string Cmd_UnknownCommandLineArgs {
            get {
                return ResourceManager.GetString("Cmd_UnknownCommandLineArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify architectural rules.
        /// </summary>
        public static string Cmd_VerifyArchitecturalRules {
            get {
                return ResourceManager.GetString("Cmd_VerifyArchitecturalRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser warnings:.
        /// </summary>
        public static string Cmd_Warnings {
            get {
                return ResourceManager.GetString("Cmd_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Elements.
        /// </summary>
        public static string CodeElements_Header {
            get {
                return ResourceManager.GetString("CodeElements_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Explorer.
        /// </summary>
        public static string CodeExplorer_Header {
            get {
                return ResourceManager.GetString("CodeExplorer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Explorer.
        /// </summary>
        public static string CodeExplorer_TabHeader {
            get {
                return ResourceManager.GetString("CodeExplorer_TabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Structure.
        /// </summary>
        public static string CodeStructure_Header {
            get {
                return ResourceManager.GetString("CodeStructure_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse everything.
        /// </summary>
        public static string CollapseEverything {
            get {
                return ResourceManager.GetString("CollapseEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string CollapseTree_Tooltip {
            get {
                return ResourceManager.GetString("CollapseTree_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event handler (possible errors).
        /// </summary>
        public static string Column_EventRegistration_Header {
            get {
                return ResourceManager.GetString("Column_EventRegistration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete relationships.
        /// </summary>
        public static string CompleteRelationships {
            get {
                return ResourceManager.GetString("CompleteRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete to containing types.
        /// </summary>
        public static string CompleteToTypes {
            get {
                return ResourceManager.GetString("CompleteToTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string Copy_Clipboard_Label {
            get {
                return ResourceManager.GetString("Copy_Clipboard_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy current Code Explorer graph as image to clipboard..
        /// </summary>
        public static string Copy_Clipboard_Tooltip {
            get {
                return ResourceManager.GetString("Copy_Clipboard_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy full qualified _name.
        /// </summary>
        public static string CopyFullQualifiedNameToClipboard {
            get {
                return ResourceManager.GetString("CopyFullQualifiedNameToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Code Explorer.
        /// </summary>
        public static string CopyToExplorerGraph_MenuItem {
            get {
                return ResourceManager.GetString("CopyToExplorerGraph_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involves {0} code elements.
        /// </summary>
        public static string Cycle_Groups_CodeElementsDescription {
            get {
                return ResourceManager.GetString("Cycle_Groups_CodeElementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle summary.
        /// </summary>
        public static string CycleSummary_TabHeader {
            get {
                return ResourceManager.GetString("CycleSummary_TabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default_Label {
            get {
                return ResourceManager.GetString("Default_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete from model.
        /// </summary>
        public static string DeleteFromModel_MenuItem {
            get {
                return ResourceManager.GetString("DeleteFromModel_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading data!.
        /// </summary>
        public static string DynamicGrid_LoadError {
            get {
                return ResourceManager.GetString("DynamicGrid_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string DynamicGrid_NoData {
            get {
                return ResourceManager.GetString("DynamicGrid_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Count.
        /// </summary>
        public static string ElementCount_Header {
            get {
                return ResourceManager.GetString("ElementCount_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Errors.
        /// </summary>
        public static string ErrorsAndWarnings_Errors {
            get {
                return ResourceManager.GetString("ErrorsAndWarnings_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors and warnings.
        /// </summary>
        public static string ErrorsAndWarnings_Title {
            get {
                return ResourceManager.GetString("ErrorsAndWarnings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Warnings.
        /// </summary>
        public static string ErrorsAndWarnings_Warnings {
            get {
                return ResourceManager.GetString("ErrorsAndWarnings_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit_Header {
            get {
                return ResourceManager.GetString("Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand everything.
        /// </summary>
        public static string ExpandEverything {
            get {
                return ResourceManager.GetString("ExpandEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export DGML ....
        /// </summary>
        public static string ExportDgml_Label {
            get {
                return ResourceManager.GetString("ExportDgml_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Code Explorer (expanded) graph to DGML (directed graph markup language)..
        /// </summary>
        public static string ExportDgml_Tooltip {
            get {
                return ResourceManager.GetString("ExportDgml_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export DSI ....
        /// </summary>
        public static string ExportDsi_Label {
            get {
                return ResourceManager.GetString("ExportDsi_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports the whole project to DSI (design structure import)..
        /// </summary>
        public static string ExportDsi_Tooltip {
            get {
                return ResourceManager.GetString("ExportDsi_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy PlantUml class diagram.
        /// </summary>
        public static string ExportPlantUml_Label {
            get {
                return ResourceManager.GetString("ExportPlantUml_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlantUml class diagram syntax has been copied to clipboard..
        /// </summary>
        public static string ExportPlantUml_Success {
            get {
                return ResourceManager.GetString("ExportPlantUml_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Export successful.
        /// </summary>
        public static string ExportPlantUml_Title {
            get {
                return ResourceManager.GetString("ExportPlantUml_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the Code Explorer (expanded) graph as PlantUml class diagram syntax to the clipboard..
        /// </summary>
        public static string ExportPlantUml_Tooltip {
            get {
                return ResourceManager.GetString("ExportPlantUml_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export SVG ....
        /// </summary>
        public static string ExportSvg_Label {
            get {
                return ResourceManager.GetString("ExportSvg_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Code Explorer (expanded) graph to SVG. NOTE: Sub-graphs are not implemented!.
        /// </summary>
        public static string ExportSvg_Tooltip {
            get {
                return ResourceManager.GetString("ExportSvg_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File_Header {
            get {
                return ResourceManager.GetString("File_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions to exclude projects.
        /// </summary>
        public static string FilterDialog_ProjectFilters_Tooltip {
            get {
                return ResourceManager.GetString("FilterDialog_ProjectFilters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set project exclusion filters.
        /// </summary>
        public static string FilterDialog_Title {
            get {
                return ResourceManager.GetString("FilterDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        public static string Find_Cycles_Label {
            get {
                return ResourceManager.GetString("Find_Cycles_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds cyclic code structures.
        /// </summary>
        public static string Find_Cycles_Tooltip {
            get {
                return ResourceManager.GetString("Find_Cycles_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find_Label {
            get {
                return ResourceManager.GetString("Find_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _abstractions.
        /// </summary>
        public static string FindAbstractions {
            get {
                return ResourceManager.GetString("FindAbstractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find incoming Calls.
        /// </summary>
        public static string FindIncomingCalls {
            get {
                return ResourceManager.GetString("FindIncomingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _inheritance tree.
        /// </summary>
        public static string FindInheritanceTree {
            get {
                return ResourceManager.GetString("FindInheritanceTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in _tree.
        /// </summary>
        public static string FindInTree {
            get {
                return ResourceManager.GetString("FindInTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find outgoing Calls.
        /// </summary>
        public static string FindOutgoingCalls {
            get {
                return ResourceManager.GetString("FindOutgoingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _specializations.
        /// </summary>
        public static string FindSpecializations {
            get {
                return ResourceManager.GetString("FindSpecializations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Graph.
        /// </summary>
        public static string FlatGraph_Label {
            get {
                return ResourceManager.GetString("FlatGraph_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the graph flat or hierarchical.
        /// </summary>
        public static string FlatGraph_Tooltip {
            get {
                return ResourceManager.GetString("FlatGraph_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Flow.
        /// </summary>
        public static string Flow_Label {
            get {
                return ResourceManager.GetString("Flow_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the information flow instead of dependencies between code elements.
        /// </summary>
        public static string Flow_Tooltip {
            get {
                return ResourceManager.GetString("Flow_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow incoming Calls (Heuristic).
        /// </summary>
        public static string FollowIncomingCalls {
            get {
                return ResourceManager.GetString("FollowIncomingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path.
        /// </summary>
        public static string FullPath_Label {
            get {
                return ResourceManager.GetString("FullPath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Gallery_Add {
            get {
                return ResourceManager.GetString("Gallery_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Gallery_Close {
            get {
                return ResourceManager.GetString("Gallery_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-click to preview, double-click to load.
        /// </summary>
        public static string Gallery_Hint {
            get {
                return ResourceManager.GetString("Gallery_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery_Label {
            get {
                return ResourceManager.GetString("Gallery_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show gallery of available graphs..
        /// </summary>
        public static string Gallery_Tooltip {
            get {
                return ResourceManager.GetString("Gallery_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide code element types:.
        /// </summary>
        public static string GraphFilterDialog_CodeElements {
            get {
                return ResourceManager.GetString("GraphFilterDialog_CodeElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide relationship types:.
        /// </summary>
        public static string GraphFilterDialog_Relationships {
            get {
                return ResourceManager.GetString("GraphFilterDialog_Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Elements and Relationships.
        /// </summary>
        public static string GraphFilterDialog_Title {
            get {
                return ResourceManager.GetString("GraphFilterDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed rendering graph! Undo your last operation..
        /// </summary>
        public static string GraphRenderingError {
            get {
                return ResourceManager.GetString("GraphRenderingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed rendering graph. Retry without line bundling..
        /// </summary>
        public static string GraphRenderingWarning {
            get {
                return ResourceManager.GetString("GraphRenderingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_Header {
            get {
                return ResourceManager.GetString("Help_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string HideFilter_Label {
            get {
                return ResourceManager.GetString("HideFilter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide code elements and relationships from the graph.
        /// </summary>
        public static string HideFilter_Tooltip {
            get {
                return ResourceManager.GetString("HideFilter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighting.
        /// </summary>
        public static string Highlighting_Label {
            get {
                return ResourceManager.GetString("Highlighting_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing edges.
        /// </summary>
        public static string HighlightOutgoingEdges {
            get {
                return ResourceManager.GetString("HighlightOutgoingEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest non self circuit.
        /// </summary>
        public static string HighlightSelfCircuit {
            get {
                return ResourceManager.GetString("HighlightSelfCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Right-click on code element: context-sensitive commands.
        /// </summary>
        public static string Hint_Context {
            get {
                return ResourceManager.GetString("Hint_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Left-click on code element: show detail in Info tab.
        /// </summary>
        public static string Hint_DetailInfo {
            get {
                return ResourceManager.GetString("Hint_DetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Double-click on container: expand / collapse.
        /// </summary>
        public static string Hint_ExpandCollapse {
            get {
                return ResourceManager.GetString("Hint_ExpandCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Right-click on empty space: global context commands (i.e. selection).
        /// </summary>
        public static string Hint_GlobalContext {
            get {
                return ResourceManager.GetString("Hint_GlobalContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold quick help: Ctrl + Click.
        /// </summary>
        public static string Hint_HoldQuickInfo {
            get {
                return ResourceManager.GetString("Hint_HoldQuickInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Shift + left-click + mouse move: panning.
        /// </summary>
        public static string Hint_Panning {
            get {
                return ResourceManager.GetString("Hint_Panning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Ctrl + left-click: (multi) select code element.
        /// </summary>
        public static string Hint_Select {
            get {
                return ResourceManager.GetString("Hint_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Header {
            get {
                return ResourceManager.GetString("Home_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hovered edge.
        /// </summary>
        public static string Hovered_Edge_Label {
            get {
                return ResourceManager.GetString("Hovered_Edge_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import_Label {
            get {
                return ResourceManager.GetString("Import_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from _jdeps ....
        /// </summary>
        public static string ImportJdeps_Label {
            get {
                return ResourceManager.GetString("ImportJdeps_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Visual Studio _solution ....
        /// </summary>
        public static string ImportSolution_Label {
            get {
                return ResourceManager.GetString("ImportSolution_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoPanel_TabHeader {
            get {
                return ResourceManager.GetString("InfoPanel_TabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Information_Title {
            get {
                return ResourceManager.GetString("Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters cannot contain semicolons (;)..
        /// </summary>
        public static string InvalidFilter_Message {
            get {
                return ResourceManager.GetString("InvalidFilter_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filters.
        /// </summary>
        public static string InvalidFilter_Title {
            get {
                return ResourceManager.GetString("InvalidFilter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout_Label {
            get {
                return ResourceManager.GetString("Layout_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets zoom level and fits to screen.
        /// </summary>
        public static string Layout_Tooltip {
            get {
                return ResourceManager.GetString("Layout_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left to Right.
        /// </summary>
        public static string Left_To_Right_Label {
            get {
                return ResourceManager.GetString("Left_To_Right_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string Legend_Assembly {
            get {
                return ResourceManager.GetString("Legend_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Legend_Class {
            get {
                return ResourceManager.GetString("Legend_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate.
        /// </summary>
        public static string Legend_Delegate {
            get {
                return ResourceManager.GetString("Legend_Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum.
        /// </summary>
        public static string Legend_Enum {
            get {
                return ResourceManager.GetString("Legend_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Legend_Event {
            get {
                return ResourceManager.GetString("Legend_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Legend_Field {
            get {
                return ResourceManager.GetString("Legend_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string Legend_Interface {
            get {
                return ResourceManager.GetString("Legend_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend_Label {
            get {
                return ResourceManager.GetString("Legend_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Legend_Method {
            get {
                return ResourceManager.GetString("Legend_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Legend_Namespace {
            get {
                return ResourceManager.GetString("Legend_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Legend_Property {
            get {
                return ResourceManager.GetString("Legend_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Legend_Record {
            get {
                return ResourceManager.GetString("Legend_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct.
        /// </summary>
        public static string Legend_Struct {
            get {
                return ResourceManager.GetString("Legend_Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Legend.
        /// </summary>
        public static string Legend_Title {
            get {
                return ResourceManager.GetString("Legend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show color legend.
        /// </summary>
        public static string Legend_Tooltip {
            get {
                return ResourceManager.GetString("Legend_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level_Header {
            get {
                return ResourceManager.GetString("Level_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string Load_Message_Default {
            get {
                return ResourceManager.GetString("Load_Message_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Project.
        /// </summary>
        public static string LoadProject_Label {
            get {
                return ResourceManager.GetString("LoadProject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations_Label {
            get {
                return ResourceManager.GetString("Locations_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide filters are active!.
        /// </summary>
        public static string Message_FiltersAreActive {
            get {
                return ResourceManager.GetString("Message_FiltersAreActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully!.
        /// </summary>
        public static string Message_OperationCompleted_Successful {
            get {
                return ResourceManager.GetString("Message_OperationCompleted_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Code elements.
        /// </summary>
        public static string Metric_CodeElements {
            get {
                return ResourceManager.GetString("Metric_CodeElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Relationships.
        /// </summary>
        public static string Metric_Relationships {
            get {
                return ResourceManager.GetString("Metric_Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string Metrics_TabHeader {
            get {
                return ResourceManager.GetString("Metrics_TabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_Label {
            get {
                return ResourceManager.GetString("Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to undo!.
        /// </summary>
        public static string NothingToUndo_Message {
            get {
                return ResourceManager.GetString("NothingToUndo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string NothingToUndo_Title {
            get {
                return ResourceManager.GetString("NothingToUndo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed: {0}.
        /// </summary>
        public static string OperationFailed_Message {
            get {
                return ResourceManager.GetString("OperationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are failures when loading the solution. The code graph may not complete:
        ///
        ///.
        /// </summary>
        public static string Parser_FailureHeader {
            get {
                return ResourceManager.GetString("Parser_FailureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Partition (base exclusive).
        /// </summary>
        public static string Partition {
            get {
                return ResourceManager.GetString("Partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains {0} code elements.
        /// </summary>
        public static string Partition_Description {
            get {
                return ResourceManager.GetString("Partition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No distinct partitions found!.
        /// </summary>
        public static string Partitions_NoPartitions {
            get {
                return ResourceManager.GetString("Partitions_NoPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition (base inclusive).
        /// </summary>
        public static string PartitionWithBase {
            get {
                return ResourceManager.GetString("PartitionWithBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed?.
        /// </summary>
        public static string Proceed_Title {
            get {
                return ResourceManager.GetString("Proceed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project filter.
        /// </summary>
        public static string ProjectFilter_Label {
            get {
                return ResourceManager.GetString("ProjectFilter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set project exclusion filters via regular expressions.
        /// </summary>
        public static string ProjectFilter_Tooltip {
            get {
                return ResourceManager.GetString("ProjectFilter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Info.
        /// </summary>
        public static string QuickInfo_Label {
            get {
                return ResourceManager.GetString("QuickInfo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refactor.
        /// </summary>
        public static string Refactor {
            get {
                return ResourceManager.GetString("Refactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create code _element.
        /// </summary>
        public static string Refactor_CreateCodeElement {
            get {
                return ResourceManager.GetString("Refactor_CreateCodeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Move.
        /// </summary>
        public static string Refactor_MoveCodeElement {
            get {
                return ResourceManager.GetString("Refactor_MoveCodeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to &apos;{0}&apos;.
        /// </summary>
        public static string Refactor_MoveCodeElementTo {
            get {
                return ResourceManager.GetString("Refactor_MoveCodeElementTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting model elements cannot be undone. Make sure your project is saved. Do you want to proceed?.
        /// </summary>
        public static string Refactoring_DeleteFromModel_Message {
            get {
                return ResourceManager.GetString("Refactoring_DeleteFromModel_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving model elements cannot be undone. Make sure your project is saved. Do you want to proceed?.
        /// </summary>
        public static string Refactoring_Move_Message {
            get {
                return ResourceManager.GetString("Refactoring_Move_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Set as movement parent.
        /// </summary>
        public static string Refactoring_SetAsMovementParent {
            get {
                return ResourceManager.GetString("Refactoring_SetAsMovementParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Relationship_Attribute {
            get {
                return ResourceManager.GetString("Relationship_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Class.
        /// </summary>
        public static string Relationship_BaseClass {
            get {
                return ResourceManager.GetString("Relationship_BaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Method.
        /// </summary>
        public static string Relationship_BaseMethod {
            get {
                return ResourceManager.GetString("Relationship_BaseMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callee.
        /// </summary>
        public static string Relationship_Callee {
            get {
                return ResourceManager.GetString("Relationship_Callee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller.
        /// </summary>
        public static string Relationship_Caller {
            get {
                return ResourceManager.GetString("Relationship_Caller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer.
        /// </summary>
        public static string Relationship_Consumer {
            get {
                return ResourceManager.GetString("Relationship_Consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contained Element.
        /// </summary>
        public static string Relationship_ContainedElement {
            get {
                return ResourceManager.GetString("Relationship_ContainedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string Relationship_Container {
            get {
                return ResourceManager.GetString("Relationship_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Type.
        /// </summary>
        public static string Relationship_CreatedType {
            get {
                return ResourceManager.GetString("Relationship_CreatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Relationship_Creator {
            get {
                return ResourceManager.GetString("Relationship_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorated Element.
        /// </summary>
        public static string Relationship_DecoratedElement {
            get {
                return ResourceManager.GetString("Relationship_DecoratedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derived Class.
        /// </summary>
        public static string Relationship_DerivedClass {
            get {
                return ResourceManager.GetString("Relationship_DerivedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Relationship_Event {
            get {
                return ResourceManager.GetString("Relationship_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Handler.
        /// </summary>
        public static string Relationship_EventHandler {
            get {
                return ResourceManager.GetString("Relationship_EventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Invoker.
        /// </summary>
        public static string Relationship_EventInvoker {
            get {
                return ResourceManager.GetString("Relationship_EventInvoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Source.
        /// </summary>
        public static string Relationship_EventSource {
            get {
                return ResourceManager.GetString("Relationship_EventSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation.
        /// </summary>
        public static string Relationship_Implementation {
            get {
                return ResourceManager.GetString("Relationship_Implementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string Relationship_Interface {
            get {
                return ResourceManager.GetString("Relationship_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Method.
        /// </summary>
        public static string Relationship_OverrideMethod {
            get {
                return ResourceManager.GetString("Relationship_OverrideMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Relationship_Source {
            get {
                return ResourceManager.GetString("Relationship_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Relationship_Target {
            get {
                return ResourceManager.GetString("Relationship_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Element.
        /// </summary>
        public static string Relationship_UsedElement {
            get {
                return ResourceManager.GetString("Relationship_UsedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove _with children.
        /// </summary>
        public static string RemoveWithChildren {
            get {
                return ResourceManager.GetString("RemoveWithChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove from Code Explorer.
        /// </summary>
        public static string RemoveWithoutChildren {
            get {
                return ResourceManager.GetString("RemoveWithoutChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string Rendering_Label {
            get {
                return ResourceManager.GetString("Rendering_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the project so you don&apos;t have to import it again?.
        /// </summary>
        public static string Save_Message {
            get {
                return ResourceManager.GetString("Save_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Title {
            get {
                return ResourceManager.GetString("Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PNG ....
        /// </summary>
        public static string SavePng_Label {
            get {
                return ResourceManager.GetString("SavePng_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports the current visible Code Explorer to PNG..
        /// </summary>
        public static string SavePng_Tooltip {
            get {
                return ResourceManager.GetString("SavePng_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        public static string SaveProject_Label {
            get {
                return ResourceManager.GetString("SaveProject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching Cycles ....
        /// </summary>
        public static string SearchingCycles_Message {
            get {
                return ResourceManager.GetString("SearchingCycles_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in code element full name.
        ///
        ///Logical operations: space = AND, &apos;|&apos; = OR
        ///Search for type = type:xxx
        ///Search for internal code elements = source:intern      
        ///Search for external code elements = source:extern
        ///Search with resharper style = Use at least one uppercase character in a search term..
        /// </summary>
        public static string SearchPattern_Tooltip {
            get {
                return ResourceManager.GetString("SearchPattern_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: Add Parent.
        /// </summary>
        public static string SelectedAddParent {
            get {
                return ResourceManager.GetString("SelectedAddParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: Focus.
        /// </summary>
        public static string SelectedFocus {
            get {
                return ResourceManager.GetString("SelectedFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: Remove (with children).
        /// </summary>
        public static string SelectedRemoveWithChildren {
            get {
                return ResourceManager.GetString("SelectedRemoveWithChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically _add containing type.
        /// </summary>
        public static string Settings_AddContainingType {
            get {
                return ResourceManager.GetString("Settings_AddContainingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Element Warning _Limit:.
        /// </summary>
        public static string Settings_CodeElementWarningLimit {
            get {
                return ResourceManager.GetString("Settings_CodeElementWarningLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows warning when graph contains more than this number of elements.
        /// </summary>
        public static string Settings_CodeElementWarningLimit_Tooltip {
            get {
                return ResourceManager.GetString("Settings_CodeElementWarningLimit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open application settings dialog.
        /// </summary>
        public static string Settings_Header_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Header_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings are applied after a restart of the application..
        /// </summary>
        public static string Settings_Hint {
            get {
                return ResourceManager.GetString("Settings_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include _external code.
        /// </summary>
        public static string Settings_IncludeExternalCode {
            get {
                return ResourceManager.GetString("Settings_IncludeExternalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include external code when parsing the solution..
        /// </summary>
        public static string Settings_IncludeExternalCode_Tooltip {
            get {
                return ResourceManager.GetString("Settings_IncludeExternalCode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Settings.
        /// </summary>
        public static string Settings_Performance {
            get {
                return ResourceManager.GetString("Settings_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Filters.
        /// </summary>
        public static string Settings_ProjectFilters {
            get {
                return ResourceManager.GetString("Settings_ProjectFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Project Exclude _Filter:.
        /// </summary>
        public static string Settings_ProjectFilters_Text {
            get {
                return ResourceManager.GetString("Settings_ProjectFilters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions to exclude projects (separated by semicolon).
        /// </summary>
        public static string Settings_ProjectFilters_Tooltip {
            get {
                return ResourceManager.GetString("Settings_ProjectFilters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show quick help by default.
        /// </summary>
        public static string Settings_QuickHelpByDefault {
            get {
                return ResourceManager.GetString("Settings_QuickHelpByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string Settings_Rendering {
            get {
                return ResourceManager.GetString("Settings_Rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings:.
        /// </summary>
        public static string Settings_Save_Error {
            get {
                return ResourceManager.GetString("Settings_Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to their default values?.
        /// </summary>
        public static string Settings_Save_Qustion {
            get {
                return ResourceManager.GetString("Settings_Save_Qustion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string Settings_Save_Title {
            get {
                return ResourceManager.GetString("Settings_Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When adding methods or fields to the graph, automatically include their containing class/type.
        /// </summary>
        public static string Settings_Settings_AddContainingType_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Settings_AddContainingType_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Warn if hide filters are active.
        /// </summary>
        public static string Settings_WarnIfFiltersActive {
            get {
                return ResourceManager.GetString("Settings_WarnIfFiltersActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a warning if hide filters are active when performing graph operations.
        /// </summary>
        public static string Settings_WarnIfFiltersActive_Tooltip {
            get {
                return ResourceManager.GetString("Settings_WarnIfFiltersActive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer.
        /// </summary>
        public static string Tab_Analyzer {
            get {
                return ResourceManager.GetString("Tab_Analyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Groups.
        /// </summary>
        public static string Tab_Cycles {
            get {
                return ResourceManager.GetString("Tab_Cycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitions.
        /// </summary>
        public static string Tab_Partitions {
            get {
                return ResourceManager.GetString("Tab_Partitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Tab_Summary {
            get {
                return ResourceManager.GetString("Tab_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle _flag.
        /// </summary>
        public static string ToggleFlag {
            get {
                return ResourceManager.GetString("ToggleFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools_Header {
            get {
                return ResourceManager.GetString("Tools_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph contains {0} elements. It may take extremely long to render this data. 
        ///
        ///Do you want to proceed?
        ///    
        ///If you abort the graph is maintained but not rendered. Use undo to get to the previous state..
        /// </summary>
        public static string TooMuchElementsMessage {
            get {
                return ResourceManager.GetString("TooMuchElementsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed?.
        /// </summary>
        public static string TooMuchElementsTitle {
            get {
                return ResourceManager.GetString("TooMuchElementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in code element name. ENTER to start search.
        ///&apos;!&apos; Clears the search but keeps highlighting
        ///
        ///Logical operations: space = AND, &apos;|&apos; = OR
        ///Search for type = type:xxx
        ///Search for internal code elements = source:intern      
        ///Search for external code elements = source:extern
        ///Search with resharper style = Use at least one uppercase character in a search term..
        /// </summary>
        public static string TreeSearch_Tooltip {
            get {
                return ResourceManager.GetString("TreeSearch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type_Label {
            get {
                return ResourceManager.GetString("Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo_Label {
            get {
                return ResourceManager.GetString("Undo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the last operation in graph..
        /// </summary>
        public static string Undo_Tooltip {
            get {
                return ResourceManager.GetString("Undo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save/Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning_Title {
            get {
                return ResourceManager.GetString("Warning_Title", resourceCulture);
            }
        }
    }
}
