using CSharpCodeAnalyst.CodeGraph.Graph;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace CSharpCodeAnalyst.CodeParser.Parser;

/// <summary>
///     Recognizes code a tool wrote. Generated code is always parsed - it holds relationships nothing else
///     does, and dropping it would turn the code it references into dead code (the markup compiler's
///     <c>Connect</c> is the only caller of every XAML event handler, and a CommunityToolkit
///     <c>[ObservableProperty]</c> is the only thing reading the backing field). It is marked instead, so a
///     consumer can leave it out of a result it would only clutter.
///     <para>
///         The rules are Roslyn's own (<c>GeneratedCodeUtilities</c>, what every analyzer uses): a file name
///         from the known list, or an <c>&lt;auto-generated&gt;</c> comment before the first token.
///     </para>
/// </summary>
internal static class GeneratedCode
{
    /// <summary>
    ///     File names a tool owns. <c>.g.cs</c> / <c>.g.i.cs</c> come from the XAML markup compiler,
    ///     <c>.designer.cs</c> from the resx and WinForms designers.
    /// </summary>
    private static readonly string[] GeneratedFileSuffixes =
    [
        ".g.cs", ".g.i.cs", ".designer.cs", ".generated.cs", ".assemblyattributes.cs"
    ];

    private const string TemporaryGeneratedFilePrefix = "TemporaryGeneratedFile_";

    public static bool IsGeneratedFile(SyntaxTree tree)
    {
        return HasGeneratedFileName(tree.FilePath) || HasAutoGeneratedComment(tree);
    }

    /// <summary>
    ///     Whether every declaration of the element sits in a generated file.
    ///     <para>
    ///         "Every" is the point. A WPF code-behind class is <c>partial</c>: half of it is
    ///         <c>MainWindow.xaml.cs</c>, which you wrote, and half is <c>MainWindow.g.cs</c>, which the
    ///         markup compiler wrote - one element with two source locations. Asking whether *any*
    ///         declaration is generated would mark your own class; asking about the first one would make
    ///         the answer depend on the order the files were walked in. Only the generated half's own
    ///         members (<c>Connect</c>, the <c>x:Name</c> fields) are declared nowhere else, and those are
    ///         exactly the ones this is meant to catch.
    ///     </para>
    ///     <para>
    ///         An element without any source location - an assembly, a namespace - is never generated.
    ///     </para>
    /// </summary>
    public static bool IsGeneratedElement(CodeElement element, HashSet<string> generatedFilePaths)
    {
        return element.SourceLocations.Count > 0 &&
               element.SourceLocations.All(location =>
                   location.File is not null && generatedFilePaths.Contains(location.File));
    }

    private static bool HasGeneratedFileName(string? filePath)
    {
        if (string.IsNullOrEmpty(filePath))
        {
            return false;
        }

        var fileName = Path.GetFileName(filePath);

        return fileName.StartsWith(TemporaryGeneratedFilePrefix, StringComparison.OrdinalIgnoreCase) ||
               GeneratedFileSuffixes.Any(suffix => fileName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    ///     The header convention. The comment has to sit before the first token - otherwise a file merely
    ///     talking about generated code would count. This is what catches the files the name list does not:
    ///     the AssemblyInfo under obj, and anything a tool writes under its own name.
    /// </summary>
    private static bool HasAutoGeneratedComment(SyntaxTree tree)
    {
        foreach (var trivia in tree.GetRoot().GetFirstToken(true).LeadingTrivia)
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) &&
                !trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
            {
                continue;
            }

            if (trivia.ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
