//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Hand-maintained: add a getter here whenever you add a key to Strings.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpCodeAnalyst.Importers.Resources {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpCodeAnalyst.Importers.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_CancelButton {
            get {
                return ResourceManager.GetString("Common_CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OkButton {
            get {
                return ResourceManager.GetString("Common_OkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Converting Dart analyzer output ....
        /// </summary>
        public static string ImportDart_Converting {
            get {
                return ResourceManager.GetString("ImportDart_Converting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Dart SDK was found. Please install the Dart SDK or Flutte....
        /// </summary>
        public static string ImportDart_DartNotFound {
            get {
                return ResourceManager.GetString("ImportDart_DartNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analyzes a Dart or Flutter project with the Dart analyzer an....
        /// </summary>
        public static string ImportDart_Description {
            get {
                return ResourceManager.GetString("ImportDart_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import Dart or Flutter project.
        /// </summary>
        public static string ImportDart_DialogTitle {
            get {
                return ResourceManager.GetString("ImportDart_DialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        public static string ImportDart_DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ImportDart_DirectoryDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import _Dart/Flutter project ....
        /// </summary>
        public static string ImportDart_Label {
            get {
                return ResourceManager.GetString("ImportDart_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No pubspec.yaml in this directory - please select the root o....
        /// </summary>
        public static string ImportDart_NoPubspec {
            get {
                return ResourceManager.GetString("ImportDart_NoPubspec", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The project is not resolved. Please run "flutter pub get" (o....
        /// </summary>
        public static string ImportDart_NotResolved {
            get {
                return ResourceManager.GetString("ImportDart_NotResolved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparing the Dart extractor (only needed once) ....
        /// </summary>
        public static string ImportDart_PreparingTool {
            get {
                return ResourceManager.GetString("ImportDart_PreparingTool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Importing Dart project ....
        /// </summary>
        public static string ImportDart_Progress {
            get {
                return ResourceManager.GetString("ImportDart_Progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project directory (contains pubspec.yaml).
        /// </summary>
        public static string ImportDart_ProjectDirectory_Label {
            get {
                return ResourceManager.GetString("ImportDart_ProjectDirectory_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analyzing Dart sources (this can take a while on large code ....
        /// </summary>
        public static string ImportDart_RunningExtractor {
            get {
                return ResourceManager.GetString("ImportDart_RunningExtractor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Dart or Flutter project directory.
        /// </summary>
        public static string ImportDart_SelectProjectDirectoryTitle {
            get {
                return ResourceManager.GetString("ImportDart_SelectProjectDirectoryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Converting doxygen output ....
        /// </summary>
        public static string ImportDoxygen_Converting {
            get {
                return ResourceManager.GetString("ImportDoxygen_Converting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Runs doxygen over the given source directory and imports the....
        /// </summary>
        public static string ImportDoxygen_Description {
            get {
                return ResourceManager.GetString("ImportDoxygen_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import C++ or Python project.
        /// </summary>
        public static string ImportDoxygen_DialogTitle {
            get {
                return ResourceManager.GetString("ImportDoxygen_DialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        public static string ImportDoxygen_DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ImportDoxygen_DirectoryDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to doxygen was not found. Please install doxygen and make sure ....
        /// </summary>
        public static string ImportDoxygen_DoxygenNotFound {
            get {
                return ResourceManager.GetString("ImportDoxygen_DoxygenNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import _C++/Python project (doxygen) ....
        /// </summary>
        public static string ImportDoxygen_Label {
            get {
                return ResourceManager.GetString("ImportDoxygen_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ImportDoxygen_Language_Label {
            get {
                return ResourceManager.GetString("ImportDoxygen_Language_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Importing project via doxygen ....
        /// </summary>
        public static string ImportDoxygen_Progress {
            get {
                return ResourceManager.GetString("ImportDoxygen_Progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ImportDoxygen_ProjectName_Label {
            get {
                return ResourceManager.GetString("ImportDoxygen_ProjectName_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running doxygen (this can take a while on large code bases) ....
        /// </summary>
        public static string ImportDoxygen_RunningDoxygen {
            get {
                return ResourceManager.GetString("ImportDoxygen_RunningDoxygen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select source directory.
        /// </summary>
        public static string ImportDoxygen_SelectSourceDirectoryTitle {
            get {
                return ResourceManager.GetString("ImportDoxygen_SelectSourceDirectoryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source directory.
        /// </summary>
        public static string ImportDoxygen_SourceDirectory_Label {
            get {
                return ResourceManager.GetString("ImportDoxygen_SourceDirectory_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Imports a dependency file produced by the JDK's jdeps tool. ....
        /// </summary>
        public static string ImportJdeps_Description {
            get {
                return ResourceManager.GetString("ImportJdeps_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select jdeps output file.
        /// </summary>
        public static string ImportJdeps_DialogTitle {
            get {
                return ResourceManager.GetString("ImportJdeps_DialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string ImportJdeps_FileFilter {
            get {
                return ResourceManager.GetString("ImportJdeps_FileFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import from _jdeps ....
        /// </summary>
        public static string ImportJdeps_Label {
            get {
                return ResourceManager.GetString("ImportJdeps_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reads a graph written in the plain text format - the counter....
        /// </summary>
        public static string ImportPlainText_Description {
            get {
                return ResourceManager.GetString("ImportPlainText_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select plain text graph file.
        /// </summary>
        public static string ImportPlainText_DialogTitle {
            get {
                return ResourceManager.GetString("ImportPlainText_DialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string ImportPlainText_FileFilter {
            get {
                return ResourceManager.GetString("ImportPlainText_FileFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import plain text ....
        /// </summary>
        public static string ImportPlainText_Label {
            get {
                return ResourceManager.GetString("ImportPlainText_Label", resourceCulture);
            }
        }

    }
}
