//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpCodeAnalyst.Analyzers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpCodeAnalyst.Analyzers.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ineffective rules found. Every rule matches at least one code element or still enforces a constraint..
        /// </summary>
        public static string Analyzer_ArchitecturalRules_Cleanup_NothingToRemove {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_Cleanup_NothingToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} rule(s) that matched no code element..
        /// </summary>
        public static string Analyzer_ArchitecturalRules_Cleanup_Removed {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_Cleanup_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural rules.
        /// </summary>
        public static string Analyzer_ArchitecturalRules_Label {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule violations found!.
        /// </summary>
        public static string Analyzer_ArchitecturalRules_NoData {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing rules: {0}.
        /// </summary>
        public static string Analyzer_ArchitecturalRules_ParseError {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos;: the pattern &apos;{1}&apos; does not match any code element. The rule has no effect..
        /// </summary>
        public static string Analyzer_ArchitecturalRules_PatternNoMatch {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_PatternNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rule violated: the measured value of the system is {1}, at most {2} is allowed..
        /// </summary>
        public static string Analyzer_ArchitecturalRules_MetricExceeded {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_MetricExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} rule violated: {1} ({2} violation(s)).
        /// </summary>
        public static string Analyzer_ArchitecturalRules_DependencyViolation {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_DependencyViolation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} rule violated: dependency cycle &apos;{1}&apos; between {2} code elements. The Cycles view shows the group under this name..
        /// </summary>
        public static string Analyzer_ArchitecturalRules_CycleFound {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_CycleFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to max. {0}.
        /// </summary>
        public static string ArchitecturalRules_Metric_Max {
            get {
                return ResourceManager.GetString("ArchitecturalRules_Metric_Max", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} rule violated: {1} code element(s) exceed the limit of {2}..
        /// </summary>
        public static string Analyzer_ArchitecturalRules_ElementMetricExceeded {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_ElementMetricExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos;: no source metrics are available for this project. The rule cannot be checked..
        /// </summary>
        public static string Analyzer_ArchitecturalRules_NoSourceMetrics {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_NoSourceMetrics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (everything).
        /// </summary>
        public static string ArchitecturalRules_Scope_Everything {
            get {
                return ResourceManager.GetString("ArchitecturalRules_Scope_Everything", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} lines.
        /// </summary>
        public static string ArchitecturalRules_MaxLines_Value {
            get {
                return ResourceManager.GetString("ArchitecturalRules_MaxLines_Value", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validates your architectural constraints based on user-defined rules.
        /// </summary>
        public static string Analyzer_ArchitecturalRules_Tooltip {
            get {
                return ResourceManager.GetString("Analyzer_ArchitecturalRules_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule text cannot be empty.
        /// </summary>
        public static string Analyzer_Empty_Rule {
            get {
                return ResourceManager.GetString("Analyzer_Empty_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event registrations.
        /// </summary>
        public static string Analyzer_EventRegistration_Label {
            get {
                return ResourceManager.GetString("Analyzer_EventRegistration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event handler registration / un-registration imbalances found.
        /// </summary>
        public static string Analyzer_EventRegistration_NoData {
            get {
                return ResourceManager.GetString("Analyzer_EventRegistration_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds imbalances between number of event registrations / un-registrations.
        /// </summary>
        public static string Analyzer_EventRegistration_Tooltip {
            get {
                return ResourceManager.GetString("Analyzer_EventRegistration_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Complexity.
        /// </summary>
        public static string Analyzer_MethodComplexity_Label {
            get {
                return ResourceManager.GetString("Analyzer_MethodComplexity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source metrics available. Source metrics are only computed when importing a C# solution..
        /// </summary>
        public static string Analyzer_MethodComplexity_NoData {
            get {
                return ResourceManager.GetString("Analyzer_MethodComplexity_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of code and cyclomatic complexity per method..
        /// </summary>
        public static string Analyzer_MethodComplexity_Tooltip {
            get {
                return ResourceManager.GetString("Analyzer_MethodComplexity_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Metrics.
        /// </summary>
        public static string Analyzer_SystemMetrics_Label {
            get {
                return ResourceManager.GetString("Analyzer_SystemMetrics_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough types to compute system metrics..
        /// </summary>
        public static string Analyzer_SystemMetrics_NoData {
            get {
                return ResourceManager.GetString("Analyzer_SystemMetrics_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics about the code base as a whole, such as how far a change ripples through the system on average..
        /// </summary>
        public static string Analyzer_SystemMetrics_Tooltip {
            get {
                return ResourceManager.GetString("Analyzer_SystemMetrics_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Cohesion.
        /// </summary>
        public static string Analyzer_TypeCohesion_Label {
            get {
                return ResourceManager.GetString("Analyzer_TypeCohesion_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No classes with separable partitions found.
        /// </summary>
        public static string Analyzer_TypeCohesion_NoData {
            get {
                return ResourceManager.GetString("Analyzer_TypeCohesion_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds classes whose members split into independent groups (partitions) — candidates for splitting. Double-click a row to view its partitions..
        /// </summary>
        public static string Analyzer_TypeCohesion_Tooltip {
            get {
                return ResourceManager.GetString("Analyzer_TypeCohesion_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Dependencies.
        /// </summary>
        public static string Analyzer_TypeDependencies_Label {
            get {
                return ResourceManager.GetString("Analyzer_TypeDependencies_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No types found to rank.
        /// </summary>
        public static string Analyzer_TypeDependencies_NoData {
            get {
                return ResourceManager.GetString("Analyzer_TypeDependencies_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranks types by their role in the dependency structure (fan-in, fan-out, importance). Helps you find the types to understand first..
        /// </summary>
        public static string Analyzer_TypeDependencies_Tooltip {
            get {
                return ResourceManager.GetString("Analyzer_TypeDependencies_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline accepted {0}.
        /// </summary>
        public static string ArchitecturalRules_Baseline_Header {
            get {
                return ResourceManager.GetString("ArchitecturalRules_Baseline_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all rules?.
        /// </summary>
        public static string ArchitecturalRules_ClearConfirm_Message {
            get {
                return ResourceManager.GetString("ArchitecturalRules_ClearConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Clear.
        /// </summary>
        public static string ArchitecturalRules_ClearConfirm_Title {
            get {
                return ResourceManager.GetString("ArchitecturalRules_ClearConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated from the current assembly structure {0}. Review and adjust..
        /// </summary>
        public static string ArchitecturalRules_Generated_Header {
            get {
                return ResourceManager.GetString("ArchitecturalRules_Generated_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load rules.
        /// </summary>
        public static string ArchitecturalRules_LoadDialog_Title {
            get {
                return ResourceManager.GetString("ArchitecturalRules_LoadDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file: {0}.
        /// </summary>
        public static string ArchitecturalRules_LoadFileError_Message {
            get {
                return ResourceManager.GetString("ArchitecturalRules_LoadFileError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save rules.
        /// </summary>
        public static string ArchitecturalRules_SaveDialog_Title {
            get {
                return ResourceManager.GetString("ArchitecturalRules_SaveDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file: {0}.
        /// </summary>
        public static string ArchitecturalRules_SaveFileError_Message {
            get {
                return ResourceManager.GetString("ArchitecturalRules_SaveFileError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules saved successfully!.
        /// </summary>
        public static string ArchitecturalRules_SaveFileSuccess_Message {
            get {
                return ResourceManager.GetString("ArchitecturalRules_SaveFileSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural rules configuration.
        /// </summary>
        public static string ArchitecturalRules_Title {
            get {
                return ResourceManager.GetString("ArchitecturalRules_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four rules are supported:
        ///
        ///DENY — Forbids dependencies from source to target
        ///RESTRICT — Allows only specified dependencies
        ///ISOLATE — Completely isolates the source from external dependencies
        ///ALLOW — Defines an exception. Suppresses matching violations found by the other rules.
        ///
        ///Patterns:
        ///MyApp.Business → exact match
        ///MyApp.Business.* → element + direct children
        ///MyApp.Business.** → element + all descendants
        ///
        ///Examples:
        ///DENY MyApp.Business.** -&gt; MyApp.Data.**
        ///RESTRICT MyApp.Controllers.** -&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ArchitectureRules_Info {
            get {
                return ResourceManager.GetString("ArchitectureRules_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Close_Button {
            get {
                return ResourceManager.GetString("Close_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (!) Invalid relationship with missing elements..
        /// </summary>
        public static string Cmd_InvalidRelationship {
            get {
                return ResourceManager.GetString("Cmd_InvalidRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule violations found..
        /// </summary>
        public static string Cmd_NoRuleViolations {
            get {
                return ResourceManager.GetString("Cmd_NoRuleViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Rule Type: {0}.
        /// </summary>
        public static string Cmd_RuleTypeLine {
            get {
                return ResourceManager.GetString("Cmd_RuleTypeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations.
        /// </summary>
        public static string Cmd_ViolationsHeader {
            get {
                return ResourceManager.GetString("Cmd_ViolationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Cmd_WarningsHeader {
            get {
                return ResourceManager.GetString("Cmd_WarningsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Type.
        /// </summary>
        public static string Column_ArchitecturalRules_RuleType {
            get {
                return ResourceManager.GetString("Column_ArchitecturalRules_RuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Column_ArchitecturalRules_Source {
            get {
                return ResourceManager.GetString("Column_ArchitecturalRules_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Column_ArchitecturalRules_Target {
            get {
                return ResourceManager.GetString("Column_ArchitecturalRules_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations.
        /// </summary>
        public static string Column_ArchitecturalRules_Violations {
            get {
                return ResourceManager.GetString("Column_ArchitecturalRules_Violations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event handler (possible errors).
        /// </summary>
        public static string Column_EventRegistration_Header {
            get {
                return ResourceManager.GetString("Column_EventRegistration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Column_MethodComplexity_Code {
            get {
                return ResourceManager.GetString("Column_MethodComplexity_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment %.
        /// </summary>
        public static string Column_MethodComplexity_CommentRatio {
            get {
                return ResourceManager.GetString("Column_MethodComplexity_CommentRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Column_MethodComplexity_Comments {
            get {
                return ResourceManager.GetString("Column_MethodComplexity_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity.
        /// </summary>
        public static string Column_MethodComplexity_Complexity {
            get {
                return ResourceManager.GetString("Column_MethodComplexity_Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Column_MethodComplexity_Method {
            get {
                return ResourceManager.GetString("Column_MethodComplexity_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements.
        /// </summary>
        public static string Column_MethodComplexity_Statements {
            get {
                return ResourceManager.GetString("Column_MethodComplexity_Statements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Column_SystemMetrics_Description {
            get {
                return ResourceManager.GetString("Column_SystemMetrics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string Column_SystemMetrics_Metric {
            get {
                return ResourceManager.GetString("Column_SystemMetrics_Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Column_SystemMetrics_Value {
            get {
                return ResourceManager.GetString("Column_SystemMetrics_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Column_TypeCohesion_Class {
            get {
                return ResourceManager.GetString("Column_TypeCohesion_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest %.
        /// </summary>
        public static string Column_TypeCohesion_LargestPartition {
            get {
                return ResourceManager.GetString("Column_TypeCohesion_LargestPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Column_TypeCohesion_Members {
            get {
                return ResourceManager.GetString("Column_TypeCohesion_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitions.
        /// </summary>
        public static string Column_TypeCohesion_Partitions {
            get {
                return ResourceManager.GetString("Column_TypeCohesion_Partitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast radius.
        /// </summary>
        public static string Column_TypeDependencies_BlastRadius {
            get {
                return ResourceManager.GetString("Column_TypeDependencies_BlastRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Column_TypeDependencies_Element {
            get {
                return ResourceManager.GetString("Column_TypeDependencies_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan-in.
        /// </summary>
        public static string Column_TypeDependencies_FanIn {
            get {
                return ResourceManager.GetString("Column_TypeDependencies_FanIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan-out.
        /// </summary>
        public static string Column_TypeDependencies_FanOut {
            get {
                return ResourceManager.GetString("Column_TypeDependencies_FanOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Column_TypeDependencies_Rank {
            get {
                return ResourceManager.GetString("Column_TypeDependencies_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Column_TypeDependencies_Score {
            get {
                return ResourceManager.GetString("Column_TypeDependencies_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Code Explorer.
        /// </summary>
        public static string CopyToExplorerGraph_MenuItem {
            get {
                return ResourceManager.GetString("CopyToExplorerGraph_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to code.
        /// </summary>
        public static string JumpToCode {
            get {
                return ResourceManager.GetString("JumpToCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed: {0}.
        /// </summary>
        public static string OperationFailed_Message {
            get {
                return ResourceManager.GetString("OperationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept _Baseline.
        /// </summary>
        public static string Rules_AcceptBaseline {
            get {
                return ResourceManager.GetString("Rules_AcceptBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds an ALLOW exception for every current violation, so only new violations are reported from now on. Use this to introduce rules into an existing code base..
        /// </summary>
        public static string Rules_AcceptBaseline_Tooltip {
            get {
                return ResourceManager.GetString("Rules_AcceptBaseline_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear.
        /// </summary>
        public static string Rules_Clear {
            get {
                return ResourceManager.GetString("Rules_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Generate rules.
        /// </summary>
        public static string Rules_Generate {
            get {
                return ResourceManager.GetString("Rules_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrites all rules (no confirmation) with a generated set that freezes the current assembly-level dependency structure. A good starting point you can then refine..
        /// </summary>
        public static string Rules_Generate_Tooltip {
            get {
                return ResourceManager.GetString("Rules_Generate_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the architectural rules for your solution:.
        /// </summary>
        public static string Rules_Header {
            get {
                return ResourceManager.GetString("Rules_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load from file....
        /// </summary>
        public static string Rules_LoadFromFile {
            get {
                return ResourceManager.GetString("Rules_LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove _unused rules.
        /// </summary>
        public static string Rules_RemoveUnused {
            get {
                return ResourceManager.GetString("Rules_RemoveUnused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes rules that match no code element and therefore have no effect. Rules that still enforce something are kept..
        /// </summary>
        public static string Rules_RemoveUnused_Tooltip {
            get {
                return ResourceManager.GetString("Rules_RemoveUnused_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules definition.
        /// </summary>
        public static string Rules_RuleDefinition {
            get {
                return ResourceManager.GetString("Rules_RuleDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save to file....
        /// </summary>
        public static string Rules_SaveToFile {
            get {
                return ResourceManager.GetString("Rules_SaveToFile", resourceCulture);
            }
        }

        public static string Rules_CopyCommandLine {
            get {
                return ResourceManager.GetString("Rules_CopyCommandLine", resourceCulture);
            }
        }

        public static string Rules_CopyCommandLine_Tooltip {
            get {
                return ResourceManager.GetString("Rules_CopyCommandLine_Tooltip", resourceCulture);
            }
        }

        public static string Rules_CommandLineCopied {
            get {
                return ResourceManager.GetString("Rules_CommandLineCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No violations found..
        /// </summary>
        public static string Rules_Status_Clean {
            get {
                return ResourceManager.GetString("Rules_Status_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} violation(s) found — see the result table..
        /// </summary>
        public static string Rules_Status_Violations {
            get {
                return ResourceManager.GetString("Rules_Status_Violations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} warning(s) and {1} violation(s) — see the message and the result table..
        /// </summary>
        public static string Rules_Status_Warnings {
            get {
                return ResourceManager.GetString("Rules_Status_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show partitions.
        /// </summary>
        public static string ShowPartitions {
            get {
                return ResourceManager.GetString("ShowPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success_Title {
            get {
                return ResourceManager.GetString("Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of types in the system that are part of a dependency cycle.
        ///Lower is better. 0% means the type graph is acyclic..
        /// </summary>
        public static string SystemMetrics_Cyclicity_Description {
            get {
                return ResourceManager.GetString("SystemMetrics_Cyclicity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclicity.
        /// </summary>
        public static string SystemMetrics_Cyclicity_Name {
            get {
                return ResourceManager.GetString("SystemMetrics_Cyclicity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average percentage of types in the system that are transitively reachable from a randomly chosen type.
        ///Lower is better. Focus on the trend across imports rather than the absolute value..
        /// </summary>
        public static string SystemMetrics_PropagationCost_Description {
            get {
                return ResourceManager.GetString("SystemMetrics_PropagationCost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propagation cost.
        /// </summary>
        public static string SystemMetrics_PropagationCost_Name {
            get {
                return ResourceManager.GetString("SystemMetrics_PropagationCost_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinct directed type-to-type dependencies..
        /// </summary>
        public static string SystemMetrics_TypeDependencies_Description {
            get {
                return ResourceManager.GetString("SystemMetrics_TypeDependencies_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type dependencies.
        /// </summary>
        public static string SystemMetrics_TypeDependencies_Name {
            get {
                return ResourceManager.GetString("SystemMetrics_TypeDependencies_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of internal types the metrics are based on..
        /// </summary>
        public static string SystemMetrics_TypesAnalyzed_Description {
            get {
                return ResourceManager.GetString("SystemMetrics_TypesAnalyzed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types analyzed.
        /// </summary>
        public static string SystemMetrics_TypesAnalyzed_Name {
            get {
                return ResourceManager.GetString("SystemMetrics_TypesAnalyzed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save/_Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
